import "server-only";
import { createPublicKey, verify } from "node:crypto";

/**
 * GraniteOS licensing — the app will not run without a valid, signed license.
 *
 * A license is an Ed25519-signed token: base64url(JSON payload) + "." +
 * base64url(signature). Only the PUBLIC key lives here; licenses are minted with
 * the private key (kept by the vendor, never shipped). Forging is infeasible.
 *
 * The license token is supplied at runtime via env GRANITEOS_LICENSE.
 */

// Public verification key (safe to ship). Generated by scripts/license-keygen.mjs.
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAI+PbhiAKxuVk//94ihLAD7/OWIBNGtOampr5cw2h1RQ=
-----END PUBLIC KEY-----`;

export type LicenseStatus = {
  valid: boolean;
  reason?: "missing" | "malformed" | "bad-signature" | "expired" | "wrong-domain";
  company?: string;
  plan?: string;
  expiresAt?: string; // ISO
};

type Payload = { company: string; plan: string; iat: number; exp: number; domain: string | null };

export function verifyLicense(host?: string): LicenseStatus {
  const token = process.env.GRANITEOS_LICENSE?.trim();
  if (!token) return { valid: false, reason: "missing" };

  const dot = token.indexOf(".");
  if (dot <= 0) return { valid: false, reason: "malformed" };
  const body = token.slice(0, dot);
  const sigB64 = token.slice(dot + 1);

  // 1) signature
  try {
    const ok = verify(
      null,
      Buffer.from(body),
      createPublicKey(PUBLIC_KEY_PEM),
      Buffer.from(sigB64, "base64url"),
    );
    if (!ok) return { valid: false, reason: "bad-signature" };
  } catch {
    return { valid: false, reason: "bad-signature" };
  }

  // 2) payload
  let p: Payload;
  try {
    p = JSON.parse(Buffer.from(body, "base64url").toString("utf8"));
  } catch {
    return { valid: false, reason: "malformed" };
  }
  const expiresAt = new Date(p.exp * 1000).toISOString();

  // 3) expiry
  if (p.exp * 1000 < Date.now())
    return { valid: false, reason: "expired", company: p.company, plan: p.plan, expiresAt };

  // 4) optional domain lock (host without port)
  if (p.domain && host) {
    const h = host.split(":")[0].toLowerCase();
    if (h !== p.domain.toLowerCase() && h !== "localhost" && h !== "127.0.0.1")
      return { valid: false, reason: "wrong-domain", company: p.company, plan: p.plan, expiresAt };
  }

  return { valid: true, company: p.company, plan: p.plan, expiresAt };
}
